export const INVISIBILITY_CONFIG = Object.freeze({
  processingScale: 1,
  maskStaleAfterMs: 500,
  personThresholdLow: 0.38,
  personThresholdHigh: 0.62,
  dilationRadiusPx: 3,
  edgeFeatherEnabled: true,
  featherRadiusPx: 9,
  temporalSmoothing: 0.68,
  fastMotionSmoothing: 0.2,
  fastMotionChangeLow: 0.015,
  fastMotionChangeHigh: 0.08,
  personAlphaThreshold: 128,
  minimumPersonCoverage: 0.0002,
  backgroundBlendStrength: 1,
  colorMatchingEnabled: true,
  colorMatchUpdateIntervalMs: 300,
  colorMatchSampleWidth: 64,
  colorMatchSampleHeight: 36,
  colorMatchMaskExclusionAlpha: 0.05,
  colorMatchSmoothing: 0.8,
  colorMatchStrength: 0.85,
  colorMatchMaximumScaleDelta: 0.12,
  colorMismatchWarningThreshold: 0.08,
})
